theme: jekyll-theme-tactile

topnav_title:  Azure DevOps Demo Generator
# this appears on the top navigation bar next to the home button

site_title: Azure DevOps Demo Generator
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)

github:
  is_project_page: false
